# Usamos una imagen ligera de Go
FROM golang:1.21-alpine

# Creamos una carpeta de trabajo
WORKDIR /app

# Copiamos los archivos
COPY . .

# Instalamos las librerías necesarias
RUN go mod init radio-server && go mod tidy

# Compilamos el programa
RUN go build -o main .

# Exponemos el puerto para internet
EXPOSE 8080

# Comando para arrancar el servidor
CMD ["./main"]